### ISSUE TITLE
MileStone

### ISSUE THREAD

**Issue by kyohei-p** [kyohei-p/Nominate-App#1]
- [ ]  環境構築（Next.js, Prismaのインストール）
- [ ]  DBの選定・導入（SQLite or PostgreSQL）
- [ ]  ER図作成
- [ ] ユーザーストーリー
- [ ]  ~~テーブル定義~~
- [ ]  UI設計（Figmaデザイン）
- [ ] コンポーネント設計（AtomicDesign, [ChakraUI](https://v2.chakra-ui.com/)など）
- [ ]  実装
- [ ]  ユニットテスト（Jestなど）
- [ ] デプロイ（[Vercel](https://vercel.com/)）

**Comment by kyohei-p** [comment]
> * [ ]   環境構築（Next.js, Prismaのインストール）
> * [ ]   DBの選定・導入（SQLite or PostgreSQL）
> * [ ]   ER図作成
> * [ ]  ユーザーストーリー
> * [ ]   テーブル定義
> * [ ]   UI設計（Figmaデザイン）
> * [ ]  コンポーネント設計（AtomicDesign, [ChakraUI](https://v2.chakra-ui.com/)など）
> * [ ]   実装
> * [ ]   ユニットテスト（Jestなど）
> * [ ]  デプロイ（[Vercel](https://vercel.com/)）

[Trello](https://trello.com/b/mM6LM2l4/%E6%8C%87%E5%90%8D%E3%82%A2%E3%83%97%E3%83%AA-by-nextjs)へ移行

今回の目的はあくまでNext.jsを使えるようになること。
